parameters:
    html2pdf.host: localhost
    html2pdf.port: 8082


services:
    html2pdf.curl_protocol:
        class: carlescliment\Html2PdfServiceBundle\Bridge\CurlProtocol
    html2pdf.bridge:
        class: carlescliment\Html2PdfServiceBundle\Bridge\Html2PdfBridge
        arguments: ["@html2pdf.curl_protocol", "%html2pdf.host%", "%html2pdf.port%"]
