parameters:
    html2pdf.host: localhost
    html2pdf.port: 8082


services:
    html2pdf.curl_wrapper:
        class: carlescliment\Html2PdfServiceBundle\Bridge\CurlWrapper
    html2pdf.fopen_wrapper:
        class: carlescliment\Html2PdfServiceBundle\Bridge\FileOpenWrapper
    html2pdf.bridge:
        class: carlescliment\Html2PdfServiceBundle\Bridge\SimpleHtml2PdfBridge
        arguments: ["@html2pdf.fopen_wrapper", "%html2pdf.host%", "%html2pdf.port%"]
